=== pypi-data/pypi-mirror-118/packages/pyqtdarktheme/PyQtDarkTheme-0.1.3-py3-none-any.whl/qdarktheme/theme/validate.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "The json schema for validating color map file",
    "description": "The root schema comprises the entire JSON document.",
    "definitions": {
        "color_code": {
            "type": "string"
        }
    },
    "required": [
        "main_theme",
        "base",
        "highlight",
        "sub-highlight",
        "highlight-disabled",
        "warning",
        "dangerous",
        "text",
        "highlight-text",
        "text-disabled",
        "border",
        "popup",
        "popup-text",
        "popup-item-selected",
        "statusbar",
        "statusbar-button-hover",
        "statusbar-button-pressed",
        "statusbar-button-checked",
        "statusbar-button-disabled",
        "menubar",
        "menubar-hover",
        "menubar-item-selected",
        "toolbar",
        "toolbar-button-hover",
        "toolbar-button-pressed",
        "toolbar-button-checked",
        "toolbar-button-disabled",
        "scrollbar-handle",
        "scrollbar-handle-hover",
        "progressbar-chunk",
        "progressbar-text",
        "button-hover",
        "button-pressed",
        "button-checked",
        "button-disabled",
        "input-line",
        "input-line-border",
        "input-line-button-hover",
        "slider-subpage-handle",
        "slider-handle-hover",
        "slider-addpage",
        "tabbar-button-hover",
        "dockwidget-titlebar",
        "toolbox-tab",
        "scrollarea-highlight",
        "scrollarea-highlight-disabled",
        "scrollarea-highlight-text",
        "itemview-alternate",
        "itemview-item-hover",
        "itemview-highlight-nonactive",
        "textedit",
        "textedit-highlight",
        "listview-item-hover",
        "headerview-section",
        "headerview-text-active",
        "tableview",
        "tableview-gridline",
        "tableview-highlight-text",
        "contained-button",
        "contained-button-hover",
        "contained-button-pressed",
        "contained-button-border-pressed",
        "contained-button-checked",
        "contained-button-disabled",
        "sidebar",
        "sidebar-button-hover",
        "sidebar-button-pressed",
        "sidebar-button-checked",
        "sidebar-button-disabled"
    ],
    "additionalProperties": false,
    "properties": {
        "main_theme": {
            "description": "The main theme of this theme. Chose dark or light",
            "enum": [
                "dark",
                "light"
            ],
            "$ref": "#/definitions/color_code"
        },
        "base": {
            "description": "Main background color",
            "$ref": "#/definitions/color_code"
        },
        "highlight": {
            "description": "Main Highlight color",
            "$ref": "#/definitions/color_code"
        },
        "sub-highlight": {
            "description": "Sub highlight color of QTableview",
            "$ref": "#/definitions/color_code"
        },
        "highlight-disabled": {
            "description": "Disabled main Highlight color",
            "$ref": "#/definitions/color_code"
        },
        "warning": {
            "description": "Warning color",
            "$ref": "#/definitions/color_code"
        },
        "dangerous": {
            "description": "Dangerous color",
            "$ref": "#/definitions/color_code"
        },
        "text": {
            "description": "Main text color",
            "$ref": "#/definitions/color_code"
        },
        "highlight-text": {
            "description": "Main highlight text color",
            "$ref": "#/definitions/color_code"
        },
        "text-disabled": {
            "description": "Disabled main text color",
            "$ref": "#/definitions/color_code"
        },
        "border": {
            "description": "Border color",
            "$ref": "#/definitions/color_code"
        },
        "popup": {
            "description": "Pop-up color",
            "$ref": "#/definitions/color_code"
        },
        "popup-text": {
            "description": "Pop-up text color",
            "$ref": "#/definitions/color_code"
        },
        "popup-item-selected": {
            "description": "Selected pop-up color",
            "$ref": "#/definitions/color_code"
        },
        "statusbar": {
            "description": "QStatusBar background color",
            "$ref": "#/definitions/color_code"
        },
        "statusbar-button-hover": {
            "description": "Hovered button color in statusbar",
            "$ref": "#/definitions/color_code"
        },
        "statusbar-button-pressed": {
            "description": "Pressed button color in statusbar",
            "$ref": "#/definitions/color_code"
        },
        "statusbar-button-checked": {
            "description": "Checked button color in statusbar",
            "$ref": "#/definitions/color_code"
        },
        "statusbar-button-disabled": {
            "description": "Disabled button color in statusbar",
            "$ref": "#/definitions/color_code"
        },
        "menubar": {
            "description": "QMenuBar background color",
            "$ref": "#/definitions/color_code"
        },
        "menubar-hover": {
            "description": "Hovered QMenuBar background color",
            "$ref": "#/definitions/color_code"
        },
        "menubar-item-selected": {
            "description": "Selected item color in QMenuBar",
            "$ref": "#/definitions/color_code"
        },
        "toolbar": {
            "description": "QToolBar background color",
            "$ref": "#/definitions/color_code"
        },
        "toolbar-button-hover": {
            "description": "Hovered button color in QToolBar",
            "$ref": "#/definitions/color_code"
        },
        "toolbar-button-pressed": {
            "description": "Pressed button color in QToolBar",
            "$ref": "#/definitions/color_code"
        },
        "toolbar-button-checked": {
            "description": "Checked button color in QToolBar",
            "$ref": "#/definitions/color_code"
        },
        "toolbar-button-disabled": {
            "description": "Disabled button color in QToolBar",
            "$ref": "#/definitions/color_code"
        },
        "scrollbar-handle": {
            "description": "QScrollBar handle color",
            "$ref": "#/definitions/color_code"
        },
        "scrollbar-handle-hover": {
            "description": "Hovered QScrollBar color",
            "$ref": "#/definitions/color_code"
        },
        "progressbar-chunk": {
            "description": "QProgressBar chunk color",
            "$ref": "#/definitions/color_code"
        },
        "progressbar-text": {
            "description": "QProgressBar text color",
            "$ref": "#/definitions/color_code"
        },
        "button-hover": {
            "description": "Hovered button color",
            "$ref": "#/definitions/color_code"
        },
        "button-pressed": {
            "description": "Pressed button color",
            "$ref": "#/definitions/color_code"
        },
        "button-checked": {
            "description": "Checked button color",
            "$ref": "#/definitions/color_code"
        },
        "button-disabled": {
            "description": "Disabled button color",
            "$ref": "#/definitions/color_code"
        },
        "input-line": {
            "description": "Input box color like QComboBox, QLineEdit and QSpinBox",
            "$ref": "#/definitions/color_code"
        },
        "input-line-border": {
            "description": "Input box border color",
            "$ref": "#/definitions/color_code"
        },
        "input-line-button-hover": {
            "description": "Hovered button of input line",
            "$ref": "#/definitions/color_code"
        },
        "slider-subpage-handle": {
            "description": "Sub page and handle color of QSlider",
            "$ref": "#/definitions/color_code"
        },
        "slider-addpage": {
            "description": "Add page color of QSlider",
            "$ref": "#/definitions/color_code"
        },
        "slider-handle-hover": {
            "description": "Hovered handle color of QSlider",
            "$ref": "#/definitions/color_code"
        },
        "tabbar-button-hover": {
            "description": "Hovered button color of QTabBar",
            "$ref": "#/definitions/color_code"
        },
        "dockwidget-titlebar": {
            "description": "Title bar color",
            "$ref": "#/definitions/color_code"
        },
        "toolbox-tab": {
            "description": "QToolBox tab color",
            "$ref": "#/definitions/color_code"
        },
        "scrollarea-highlight": {
            "description": "QScrollArea highlight color",
            "$ref": "#/definitions/color_code"
        },
        "scrollarea-highlight-disabled": {
            "description": "Disabled QScrollArea highlight color",
            "$ref": "#/definitions/color_code"
        },
        "scrollarea-highlight-text": {
            "description": "Text highlight color of scrollarea",
            "$ref": "#/definitions/color_code"
        },
        "itemview-alternate": {
            "description": "ItemView alternate color",
            "$ref": "#/definitions/color_code"
        },
        "itemview-item-hover": {
            "description": "Hovered item color of itemview",
            "$ref": "#/definitions/color_code"
        },
        "itemview-highlight-nonactive": {
            "description": "Non-activated highlight color of itemview",
            "$ref": "#/definitions/color_code"
        },
        "textedit": {
            "description": "Textedit color",
            "$ref": "#/definitions/color_code"
        },
        "textedit-highlight": {
            "description": "Textedit highlight color",
            "$ref": "#/definitions/color_code"
        },
        "listview-item-hover": {
            "description": "Hovered listview item",
            "$ref": "#/definitions/color_code"
        },
        "headerview-section": {
            "description": "QHeaderview section color",
            "$ref": "#/definitions/color_code"
        },
        "headerview-text-active": {
            "description": "QHeaderview active section text color",
            "$ref": "#/definitions/color_code"
        },
        "tableview": {
            "description": "QTableview color",
            "$ref": "#/definitions/color_code"
        },
        "tableview-gridline": {
            "description": "QTableview grid line color",
            "$ref": "#/definitions/color_code"
        },
        "tableview-highlight-text": {
            "description": "QTableview highlight text color",
            "$ref": "#/definitions/color_code"
        },
        "contained-button": {
            "description": "Contained button color",
            "$ref": "#/definitions/color_code"
        },
        "contained-button-hover": {
            "description": "Hovered contained button color",
            "$ref": "#/definitions/color_code"
        },
        "contained-button-pressed": {
            "description": "Pressed contained button color",
            "$ref": "#/definitions/color_code"
        },
        "contained-button-border-pressed": {
            "description": "Border color of pressed contained button",
            "$ref": "#/definitions/color_code"
        },
        "contained-button-checked": {
            "description": "Checked contained button color",
            "$ref": "#/definitions/color_code"
        },
        "contained-button-disabled": {
            "description": "Disabled contained button color",
            "$ref": "#/definitions/color_code"
        },
        "sidebar": {
            "description": "SideBar background color",
            "$ref": "#/definitions/color_code"
        },
        "sidebar-button-hover": {
            "description": "Hovered button color in SideBar",
            "$ref": "#/definitions/color_code"
        },
        "sidebar-button-pressed": {
            "description": "Pressed button color in SideBar",
            "$ref": "#/definitions/color_code"
        },
        "sidebar-button-checked": {
            "description": "Checked button color in SideBar",
            "$ref": "#/definitions/color_code"
        },
        "sidebar-button-disabled": {
            "description": "Disabled button color in SideBar",
            "$ref": "#/definitions/color_code"
        }
    }
}

=== pypi-data/pypi-mirror-118/packages/pyqtdarktheme/PyQtDarkTheme-0.1.3.tar.gz/PyQtDarkTheme-0.1.3/qdarktheme/theme/light.json
{
    "main_theme": "light",
    "base": "#f8f9fa",
    "highlight": "#0081db",
    "sub-highlight": "#0081db",
    "highlight-disabled": "#dadce0",
    "warning": "#a68400",
    "dangerous": "#cf6156",
    "text": "#4d5157",
    "highlight-text": "#f8f9fa",
    "text-disabled": "#babdc2",
    "border": "#dadce0",
    "popup": "#ffffff",
    "popup-text": "#4d5157",
    "popup-item-selected": "#dadce0",
    "statusbar": "#dfe1e5",
    "statusbar-button-hover": "#d1d4da",
    "statusbar-button-pressed": "#c3c7ce",
    "statusbar-button-checked": "#c3c7ce",
    "statusbar-button-disabled": "#edeef0",
    "menubar": "#f8f9fa",
    "menubar-hover": "#dadce0",
    "menubar-item-selected": "#dadce0",
    "toolbar": "#ebebeb",
    "toolbar-button-hover": "#d7d7d7",
    "toolbar-button-pressed": "#c4c4c4",
    "toolbar-button-checked": "#c4c4c4",
    "toolbar-button-disabled": "#ffffff",
    "scrollbar-handle": "#9b9b9d",
    "scrollbar-handle-hover": "#757577",
    "progressbar-chunk": "#0081db",
    "progressbar-text": "#4d5157",
    "button-hover": "#e2eafb",
    "button-pressed": "#b5caf4",
    "button-checked": "#b5caf4",
    "button-disabled": "#dadce0",
    "input-line": "#f8f9fa",
    "input-line-border": "#dadce0",
    "input-line-button-hover": "#e2eafb",
    "slider-subpage-handle": "#0081db",
    "slider-handle-hover": "#7fa6e4",
    "slider-addpage": "#dadce0",
    "tabbar-button-hover": "#0081db",
    "dockwidget-titlebar": "#edeef0",
    "toolbox-tab": "#edeef0",
    "scrollarea-highlight": "#0081db",
    "scrollarea-highlight-disabled": "#0081db",
    "scrollarea-highlight-text": "#4d5157",
    "itemview-alternate": "#e9ecef",
    "itemview-item-hover": "#d3d3d3",
    "itemview-highlight-nonactive": "#e4e6f2",
    "textedit": "#ffffff",
    "textedit-highlight": "#a2d8ff",
    "tableview-highlight-text": "#e4e7eb",
    "listview-item-hover": "#d3d3d3",
    "headerview-section": "#dadce0",
    "headerview-text-active": "#0081db",
    "tableview": "#ffffff",
    "tableview-gridline": "#58595c",
    "contained-button": "#1c73e8",
    "contained-button-hover": "#3781ea",
    "contained-button-pressed": "#7ba9f2",
    "contained-button-border-pressed": "#a9c7f7",
    "contained-button-checked": "#4a90ed",
    "contained-button-disabled": "#dadce0",
    "sidebar": "#333333",
    "sidebar-button-hover": "#44464a",
    "sidebar-button-pressed": "#4f5054",
    "sidebar-button-checked": "#e4e7eb",
    "sidebar-button-disabled": "#202124"
}
